### ISSUE TITLE
Swipe up and down triggers

### ISSUE THREAD

**Issue by hodossy** [SmartHome-yourself/sonoff-tx-ultimate-for-esphome#33]
Is it possible to have a swipe up/down trigger? I would like to experiment with the utlimate, to control not only the lights in the room, but jelousies as well. The idea is to swipe up to start opening the blinds, swipe down to start closing them, a swipe left/right would adjust the angle and a multitouch could stop whatever motion is active.

I tried understanding the code, but I just don't have the info how the data arrives from the touch sensor. Is there a `y` coordinate somewhere? Could you point me to a description of the data structure the touch sensor sends?

Great work, I really appretiate it!

**Comment by barth11** [comment]
I don't think it's possible. In Daniel's video you can see the lines and my understanding is, it's working when you slide across sections then it activates as left/right swipe. Since you don't cross any sections going up/down, there is no way to register the movement.
https://www.youtube.com/watch?v=naDLhX89enQ&t=314s

**Comment by hodossy** [comment]
Ahh, thanks, I missed it. I don't speak German, so I watched another video. Sad...
