### ISSUE TITLE
Vibration on touch

### ISSUE THREAD

**Issue by HAautomater** [SmartHome-yourself/sonoff-tx-ultimate-for-esphome#9]
Hi, 

with the current configuration, the vibration starts after releasing the finger. Is it possible to have it on touch, like the original firmware?

Thank you for your outstanding work!
Have a good one!

**Comment by danielscheidler** [comment]
Of course it is possible. I thought it should be the signal when the real event is fire up. So I choose the release, because in the on_touch you did not know if it will be a touch, long or multitouch. 
I never try the original FW ;) but should the vibration then only be at touch, until release or when touch and when release too?

**Comment by HAautomater** [comment]
I'am not 100% sure, how the original FW behaves, since I tried it only once ;)
But I remember the vibration on touch.

As you suggested on yt, I edited the YAML:
Added "switch.turn_on: vibra"  "on_press" and deleted it from all other functions. Works perfectly, thanks again :)
